{{- if .Values.defaultBackend.enabled }}
  {{- range .Values.defaultBackend.extraConfigMaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
  namespace: {{ include "ingress-nginx.namespace" . }}
  labels:
    {{- include "ingress-nginx.labels" $ | nindent 4 }}
    {{- with $.Values.defaultBackend.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  {{- with .data }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- end }}
{{- end }}

