options:
  # Ignore Prow provided substitutions.
  substitution_option: ALLOW_LOOSE
steps:
- name: gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20251110-7ccd542560
  dir: charts
  env:
  - NAME=ingress-nginx
  entrypoint: make
  args:
  - push
