# Exoscale
controller:
  kind: DaemonSet
  service:
    type: LoadBalancer
    externalTrafficPolicy: Local
    annotations:
      service.beta.kubernetes.io/exoscale-loadbalancer-description: "NGINX Ingress Controller load balancer"
      service.beta.kubernetes.io/exoscale-loadbalancer-service-strategy: "source-hash"
      service.beta.kubernetes.io/exoscale-loadbalancer-service-healthcheck-mode: "http"
      service.beta.kubernetes.io/exoscale-loadbalancer-service-healthcheck-uri: "/"
      service.beta.kubernetes.io/exoscale-loadbalancer-service-healthcheck-interval: "10s"
      service.beta.kubernetes.io/exoscale-loadbalancer-service-healthcheck-timeout: "3s"
      service.beta.kubernetes.io/exoscale-loadbalancer-service-healthcheck-retries: "1"
  publishService:
      enabled: true
