# NOTE: kustomize is not supported. This file exists only to be able to reference it from bases.
# https://kubectl.docs.kubernetes.io/references/kustomize/bases/
#
# ```
# namespace: ingress-nginx
# bases:
#   - github.com/kubernetes/ingress-nginx/tree/main/deploy/static/provider/kind
# ```

resources:
  - deploy.yaml
