controller:
  image:
    repository: ingress-controller/controller
    tag: 1.0.0-dev
    digest: null
  service:
    type: ClusterIP
  containerSecurityContext:
    allowPrivilegeEscalation: false
  extraModules:
    - name: opentelemetry
      image:
        registry: registry.k8s.io
        image: busybox
        tag: latest
