controller:
  image:
    repository: ingress-controller/controller
    tag: 1.0.0-dev
    digest: null
  admissionWebhooks:
    enabled: false
  service:
    type: NodePort
    nodePorts:
      tcp:
        9000: 30090
      udp:
        9001: 30091

tcp:
  9000: "default/test:8080"

udp:
  9001: "default/test:8080"
