#### THIS IS A TEMPLATE ####
# This workflow is created to be a template for every time an e2e teest is required,

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      platforms-test:
        type: string
        default: linux/amd64,linux/arm64
      platforms-publish:
        type: string
        default: linux/amd64,linux/arm64

env:
  PLATFORMS: ${{ inputs.platforms-test }}

permissions:
  contents: write
  packages: write

jobs:
  changestag:
    permissions:
      contents: read  # for dorny/paths-filter to fetch a list of changed files
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.filter.outputs.tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: dorny/paths-filter@0bc4621a3135347011ad047f9ecf449bf72ce2bd # v3.0.0
        id: filter
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: |
            tag:
              - 'images/**/TAG'

  image-build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Build
        run: |
          cd images/ && make NAME=${{ inputs.name }} build

  image-push:
    name: Push
    needs: changestag
    if: |
      (github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'kubernetes/ingress-nginx' && needs.changestag.outputs.tag == 'true')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    env:
      PLATFORMS: ${{ inputs.platforms-publish }}
    steps:
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push
      run: |
          cd images/ && make REGISTRY=ingressnginx NAME=${{ inputs.name }} push

